/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.homework.jframeQLSinhVien;

import com.homework.doituong.Lop;
import com.homework.services.quanLyLop;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOME
 */
public class danhSachLop extends javax.swing.JFrame {

    /** Creates new form danhSachLop */
    public danhSachLop() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbLop = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFLop = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(533, 507));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbLop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma lop", "Ten lop", "Giao vien chu nhiem"
            }
        ));
        jScrollPane1.setViewportView(tbLop);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tim kiem");

        txtFLop.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtFLop.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtFLopTextValueChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFLop, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtFLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private List<Lop> dsLop = new ArrayList<>();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        dsLop.clear();
        try {
            quanLyLop qlLop = new quanLyLop();
            qlLop.docDanhSachLop(dsLop);
        } catch (SQLException ex) {
            Logger.getLogger(danhSachLop.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel tbmLop = (DefaultTableModel) tbLop.getModel();
        for(Lop lop: this.dsLop){
            tbmLop.addRow(new Object[] {lop.getMaLop(),lop.getTenLop(),lop.getgVCN()});
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtFLopTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtFLopTextValueChanged
        // TODO add your handling code here:
        if(txtFLop.getText().isEmpty()){
            DefaultTableModel tbmLop = (DefaultTableModel) tbLop.getModel();
            int rowCount = tbmLop.getRowCount();
            for(int i = rowCount -1;i >= 0;i--){
                tbmLop.removeRow(i);
            }
            for(Lop lop : this.dsLop){
                tbmLop.addRow(new Object[] {lop.getMaLop(),lop.getTenLop(),lop.getgVCN()});  
            }
        }
        else{
            DefaultTableModel tbmLop  = (DefaultTableModel) tbLop.getModel();
            int rowCount = tbmLop.getRowCount();
            for(int i = rowCount -1;i >= 0;i--){
                tbmLop.removeRow(i);
            }
            for(Lop lop : this.dsLop){
                if(Objects.isNull(lop.getgVCN()) == false){
                    if(lop.getgVCN().toLowerCase().contains(txtFLop.getText().toLowerCase())||lop.getMaLop().toLowerCase().contains(txtFLop.getText().toLowerCase()) || lop.getTenLop().toLowerCase().contains(txtFLop.getText().toLowerCase())){
                        tbmLop.addRow(new Object[] {lop.getMaLop(),lop.getTenLop(),lop.getgVCN()});  
                    }
                }
                else if(txtFLop.getText().toLowerCase().contains("NULL".toLowerCase())){
                    if(Objects.isNull(lop.getgVCN())){
                        tbmLop.addRow(new Object[] {lop.getMaLop(),lop.getTenLop(),lop.getgVCN()});  
                    }
                }
            }
        }
    }//GEN-LAST:event_txtFLopTextValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(danhSachLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(danhSachLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(danhSachLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(danhSachLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new danhSachLop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLop;
    private java.awt.TextField txtFLop;
    // End of variables declaration//GEN-END:variables

}
