/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.homework.jframeQLSinhVien;

import com.homework.services.quanLySinhVien;
import com.homework.doituong.SinhVien;
import com.homework.services.Menu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
  


public class danhSachSinhVien extends javax.swing.JFrame {

    /** Creates new form danhSachSinhVien */
    public danhSachSinhVien() {
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDanhSachSinhVien = new javax.swing.JTable();
        label1 = new java.awt.Label();
        txtFTimKiem = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh sach sinh vien");
        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbDanhSachSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbDanhSachSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaSV", "Ho", "Ten", "Gioi tinh", "Que quan", "Ma Lop", "Ngay sinh"
            }
        ));
        jScrollPane1.setViewportView(tbDanhSachSinhVien);

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Tim kiem");

        txtFTimKiem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtFTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFTimKiemMouseClicked(evt);
            }
        });
        txtFTimKiem.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtFTimKiemInputMethodTextChanged(evt);
            }
        });
        txtFTimKiem.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtFTimKiemTextValueChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private List<SinhVien> dsSinhVien = new ArrayList<>();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dsSinhVien.clear();
        try {
            quanLySinhVien qlSV = new quanLySinhVien();
            qlSV.docDanhSachSinhVien(dsSinhVien);
        } catch (ParseException e) {
            throw new RuntimeException(e);
        } catch (SQLException ex) {
            Logger.getLogger(danhSachSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel tbmSinhVien = (DefaultTableModel) tbDanhSachSinhVien.getModel();
        for(SinhVien sv : this.dsSinhVien){
           tbmSinhVien.addRow(new Object[] {sv.getMaSV(),sv.getHoSV(),sv.getTenSV(),sv.getGioiTinh(),sv.getQueQuan(),sv.getMaLop(),Menu.F.format(sv.getNgaySinh())});
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtFTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFTimKiemMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFTimKiemMouseClicked

    private void txtFTimKiemInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtFTimKiemInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFTimKiemInputMethodTextChanged

    private void txtFTimKiemTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtFTimKiemTextValueChanged
        // TODO add your handling code here:
        if(txtFTimKiem.getText().isEmpty()){
            DefaultTableModel tbmSinhVien = (DefaultTableModel) tbDanhSachSinhVien.getModel();
            int rowCount = tbmSinhVien.getRowCount();
            for(int i = rowCount -1;i >= 0;i--){
                tbmSinhVien.removeRow(i);
            }
            for(SinhVien sv : this.dsSinhVien){
                tbmSinhVien.addRow(new Object[] {sv.getMaSV(),sv.getHoSV(),sv.getTenSV(),sv.getGioiTinh(),sv.getQueQuan(),sv.getMaLop(),Menu.F.format(sv.getNgaySinh())});
            
            }
        }
        else{
            DefaultTableModel tbmSinhVien = (DefaultTableModel) tbDanhSachSinhVien.getModel();
            int rowCount = tbmSinhVien.getRowCount();
            for(int i = rowCount -1;i >= 0;i--){
                tbmSinhVien.removeRow(i);
            }
            for(SinhVien sv : this.dsSinhVien){
                if(sv.getMaLop().contains(txtFTimKiem.getText()) || Integer.toString(sv.getMaSV()).contains(txtFTimKiem.getText())){
                    tbmSinhVien.addRow(new Object[] {sv.getMaSV(),sv.getHoSV(),sv.getTenSV(),sv.getGioiTinh(),sv.getQueQuan(),sv.getMaLop(),Menu.F.format(sv.getNgaySinh())});
                }
            }
        }
    }//GEN-LAST:event_txtFTimKiemTextValueChanged

    


    

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(danhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(danhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(danhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(danhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new danhSachSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTable tbDanhSachSinhVien;
    private java.awt.TextField txtFTimKiem;
    // End of variables declaration//GEN-END:variables

}
