/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.homework.jframeQLSinhVien;

import java.sql.*;
import com.homework.doituong.Lop;
import com.homework.services.quanLyLop;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HOME
 */
public class themLop extends javax.swing.JFrame {

    /** Creates new form themLop */
    public themLop() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaLop = new java.awt.TextField();
        txtTenLop = new java.awt.TextField();
        txtGVCN = new java.awt.TextField();
        btInsert = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Insert - Update");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Ma lop:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Ten lop:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("GVCN:");

        txtMaLop.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMaLop.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                txtMaLopTextValueChanged(evt);
            }
        });

        txtTenLop.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtGVCN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btInsert.setText("Insert");
        btInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertActionPerformed(evt);
            }
        });

        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btClear)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btUpdate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btInsert))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtMaLop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTenLop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGVCN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtGVCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClear)
                    .addComponent(btUpdate)
                    .addComponent(btInsert))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        txtMaLop.setText("");
        txtTenLop.setText("");
        txtGVCN.setText("");
    }//GEN-LAST:event_btClearActionPerformed
    private List<Lop> dsLop = new ArrayList<>();
    private void btInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertActionPerformed
        // TODO add your handling code here:
        if(txtMaLop.getText().isEmpty() || txtTenLop.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nhap du thong tín!", "Thong bao", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            dsLop.clear();    
            try {
                quanLyLop qlLop = new quanLyLop();
                qlLop.docDanhSachLop(dsLop);
            } catch (SQLException ex) {
                Logger.getLogger(themLop.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            boolean check = false;
            for(Lop lop : this.dsLop){
                if(lop.getMaLop().equals(txtMaLop.getText())){
                    JOptionPane.showMessageDialog(this, "Ma Lop ton tai!", "Thong bao", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            Statement stmt = null;
            try (Connection conn = com.homework.services.JdbcUtils.getConn()){   
                    if(txtGVCN.getText().isEmpty()){
                        txtGVCN.setText("null");
                    }
                   
                    String sql = "INSERT INTO lop (MaLop,TenLop,GVCN) VALUES ('"+ txtMaLop.getText() + "','"+txtTenLop.getText() + "','"+ txtGVCN.getText() + "')";
                    stmt = (Statement) conn.createStatement();
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(this,sql,"Alter",JOptionPane.INFORMATION_MESSAGE);
                

            } catch (SQLException ex) {
                Logger.getLogger(themLop.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        }
    }//GEN-LAST:event_btInsertActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
         dsLop.clear();  
         try {
                quanLyLop qlLop = new quanLyLop();
                qlLop.docDanhSachLop(dsLop);
            } catch (SQLException ex) {
                Logger.getLogger(themLop.class.getName()).log(Level.SEVERE, null, ex);
            }
         if(txtMaLop.getText().isEmpty() || txtTenLop.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nhap du thong tín!", "Thong bao", JOptionPane.ERROR_MESSAGE);
         }
         else{
             for(Lop lop : this.dsLop){
                 if(!lop.getMaLop().toLowerCase().equals(txtMaLop)){
                      txtTenLop.setText("");
                      txtGVCN.setText("");
                     JOptionPane.showMessageDialog(this,"Ma Lop khong ton tai!","Thong bao",JOptionPane.INFORMATION_MESSAGE);
                     return;
                 }
             }
          try (Connection conn = com.homework.services.JdbcUtils.getConn()){
                String query = "update lop set TenLop ='"+txtTenLop.getText() + "',GVCN ='"+ txtGVCN.getText() + "' where MaLop ='" + txtMaLop.getText() +"'";
                Statement stmt = null;
                stmt = (Statement) conn.createStatement();
                stmt.execute(query);
                JOptionPane.showMessageDialog(this,"OK!","Thong bao",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(themMonHoc.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex.toString(),"Thong bao",JOptionPane.INFORMATION_MESSAGE);
        }
         }
            
    }//GEN-LAST:event_btUpdateActionPerformed

    private void txtMaLopTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_txtMaLopTextValueChanged
        // TODO add your handling code here:
        dsLop.clear();  
         try {
                quanLyLop qlLop = new quanLyLop();
                qlLop.docDanhSachLop(dsLop);
            } catch (SQLException ex) {
                Logger.getLogger(themLop.class.getName()).log(Level.SEVERE, null, ex);
            }
        for(Lop lop : this.dsLop){
            if(lop.getMaLop().toLowerCase().equals(txtMaLop.getText().toLowerCase())){
                txtTenLop.setText(lop.getTenLop());
                txtGVCN.setText(lop.getgVCN());
            }
            else if(txtMaLop.getText().isEmpty()){
                txtTenLop.setText("");
                txtGVCN.setText("");
            }
          
            
        }
    }//GEN-LAST:event_txtMaLopTextValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new themLop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btInsert;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.TextField txtGVCN;
    private java.awt.TextField txtMaLop;
    private java.awt.TextField txtTenLop;
    // End of variables declaration//GEN-END:variables

}
